### ISSUE TITLE
cannot build or run

### ISSUE THREAD

**Issue by shntat** [LandonHarter/radium#59]
Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved. 

Install the latest PowerShell for new features and improvements! https://aka.ms/PSWindows

PS C:\radium\radium>  & 'C:\Program Files\Java\jdk-14.0.2\bin\java.exe' '-XX:+ShowCodeDetailsInExceptionMessages' '@C:\Users\Shaun\AppData\Local\Temp\cp_c6mk97q5dz0rr09cs8a7g196v.argfile' 'RadiumRuntime.Runtime' 
Exception in thread "main" java.lang.UnsatisfiedLinkError: 'long org.lwjgl.system.Callback.getNativeCallbacks(java.lang.reflect.Method[], long)'
        at org.lwjgl.system.Callback.getNativeCallbacks(Native Method)
        at org.lwjgl.system.Callback.<clinit>(Callback.java:59)
        at Radium.Input.Input.Initialize(Input.java:30)   
        at Radium.Window.CreateWindow(Window.java:73)     
        at RadiumRuntime.Runtime.Start(Runtime.java:63)   
        at RadiumRuntime.Runtime.main(Runtime.java:46)    
PS C:\radium\radium>

**Comment by LandonHarter** [comment]
How old is your computer? Do you know whether it can run LWJGL? The problem seems to be with LWJGL and not my code. If you could give me the specs of your computer or what it runs I could give you more information. My computer currently runs Windows 11 and it works fine.

**Comment by LandonHarter** [comment]
@shntat 

How old is your computer? Do you know whether it can run LWJGL? The problem seems to be with LWJGL and not my code. If you could give me the specs of your computer or what it runs I could give you more information. My computer currently runs Windows 11 and it works fine.

**Comment by LandonHarter** [comment]
Due to no response from shntat, this thread is being closed.

**Comment by shntat** [comment]
Sorry if i did not get back sooner My laptop is an alienware m15 ryzen edition r5 win 11
should not have any problems building radium.

**Comment by LandonHarter** [comment]
@shntat 

Did you build this project with just bare java or did you use gradle. Gradle is very important, it contains all the dependencies and natives required for the application to run. Also, Radium only supports Windows currently, so the natives might be for another OS.

**Comment by LandonHarter** [comment]
I just found the issue when running it with Eclipse. I am troubleshooting the problem now.

**Comment by LandonHarter** [comment]
The problem has been fixed, there is now a proper executable to run the project.
