### ISSUE TITLE
[BUG] Radium fails to load the sample project

### ISSUE THREAD

**Issue by ParoneQWERTY** [LandonHarter/radium#75]
** Describe Bug **
I don't really know if I am missing out on anything, but I have gone through all the past bug reports and the website, also downloading every version, but when I am choosing a folder for my project, it just says "This is not a Radium project, please select another folder". I downloaded this sample folder from your other github project. Maybe its just that there is a feature I am missing out? Thanks a lot.

**Comment by ParoneQWERTY** [comment]
Even when I use the project manager it still says "This is not a Radium project" and then opens a file explorer.

**Comment by LandonHarter** [comment]
Apologies for the long reply. Anyways, please attach a screenshot or a tree of the root of the project directory. The reason it says, "This is not a Radium project", is because it looks for a file named [project name].config If this file isn't found it will throw an error.

**Comment by ParoneQWERTY** [comment]
![Screenshot 2022-08-13 214818](https://user-images.githubusercontent.com/111099010/184497039-c9a6989b-353f-4ae6-8971-9d034c48d32e.png)

**Comment by ParoneQWERTY** [comment]
It does have the config file

**Comment by LandonHarter** [comment]
Can you please attach a screenshot of the project directory. Also verify that the config file has the same name as its parent folder. This is crucial and will cause errors if not.

**Comment by LandonHarter** [comment]
After experimenting, I have found that cloning the [Sample Project](https://github.com/radiumgame/sample-project) using the built in clone button on the repository renames the project to sample-project-master. As I said earlier naming is an important part of the project structure.

**Comment by LandonHarter** [comment]
I have just tested and came across the bug you have mentioned. This is because there is a space in the project name. Try doing a name like NewProject or New-Project instead. I will work on fixing this but for the time being, the project name cannot contain spaces.
