### ISSUE TITLE
https://github.com/radiumgame/sample-project MISSING [BUG]

### ISSUE THREAD

**Issue by shntat** [LandonHarter/radium#84]
** Describe Bug **
https://github.com/radiumgame/sample-project 404 error.
any chance of getting a copy?

**Comment by LandonHarter** [comment]
We have shifted from projects to be cloned to use our new project manager. Checkout radiumgame/radium-project-manager and download the exec from the releases to get started.

Edit:
I apologize for the incorrect readme, a fix will be coming out shortly.

Edit 2:
The readme has been updated, thank you for this report.
