### ISSUE TITLE
https://radiumengine.com/docs/welcome/ missing [BUG]

### ISSUE THREAD

**Issue by shntat** [LandonHarter/radium#85]
** Describe Bug **
https://radiumengine.com/docs/welcome/
documentation is missing.

**Comment by LandonHarter** [comment]
Documentation works on every browser and device I have tried. Can you send a screenshot and detail your device and browser?

**Comment by LandonHarter** [comment]
@shntat Any updates? If this issue has not been updated in the next 3 days, it will be closed.
